language: python
python:
  - "3.5"
install:
  - pip install -r ci/pip_requirements.txt
script:
  - nosetests --with-doctest --with-coverage
  - flake8 knimin setup.py scripts
after_success:
  - coveralls
