search_PDB:
    params: '-e 0.001'
    threads: 8
split_PDB:
    params: '-prob 95'

PSIBLAST_PSSM:
    params: '-j 3 -h 0.001'
    dbname: ''

search_CM:
    params: '-e 0.1'
    threads: 8
split_CM:
    params: '-e 0.1'

search_Pfam:
    params: '-e 0.1'
    threads: 8
split_Pfam:
    params: '-e 0.01 -prob 95'


MSA_hhblits:
    params: '-n 3 -e 0.001 -maxfilt 500000 -diff inf -id 99 -cov 50 -cpu 8'
    threads: 8

SEQUENCES: 'chuj'
