search_PDB:
    params: '-e 0.001'
    threads: 8
split_PDB:
    params: '--prob 95 --frag_len 10'

PSIBLAST_PSSM:
    params: '-j 3 -h 0.001'

search_CM:
    params: '-e 0.1'
    threads: 8
split_CM:
    params: '--e_val 0.1 --frag_len 40'

search_Pfam:
    params: '-e 0.1'
    threads: 8
split_Pfam:
    params: '--e_val 0.01 --prob 95 --frag_len 40'

MSA_hhblits:
    params: '-n 3 -e 0.001 -maxfilt 500000 -diff inf -id 99 -cov 50 -cpu 8'
    threads: 8
