MICROPROT_MAIN: /projects/microprot/
VERSION: 1

search_PDB:
    params: '-e 0.001'
    threads: 8
split_PDB:
    params:
        min_prob: 0.95
        min_fragment_length: 40

PSIBLAST_PSSM:
    params: '-j 3 -h 0.001'

search_CM:
    params: '-e 0.1'
    threads: 8
split_CM:
    params:
        max_evalue: 0.1
        min_fragment_length: 40

search_Pfam:
    params: '-e 0.1'
    threads: 8
split_Pfam:
    params:
        max_evalue: 0.01
        min_prob: 0.95
        min_fragment_length: 40

MSA_hhblits:
    params: '-n 1 -e 0.001 -maxfilt 500000 -diff inf -id 99 -cov 50 -cpu 8'
    threads: 8

MSA_ripe:
    cutoff: 80
    Nf: 64
